[package]
name = "rubo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
ansi_term = "0.12"
once_cell = "1.10.0"
bytesize = "1.1.0"